### PR TITLE
fix: Fixes #27

### LINKED ISSUE #27: Armour with Loud trait doesn't give disadvantage on Stealth tests
**Describe the bug**
Loud equipment trait has following description.
> The equipment is noticeably noisy. 
A weapon with the Loud Trait alerts everyone within Long Range of your presence when used to make an attack. 
**Armour with the Loud Trait imposes Disadvantage on Stealth Tests**

So there should be test modifier applied to the skill test.

**To Reproduce**

1. Create a blank Player Character (PC)
2. Create a Protection Item with added Loud trait
3. Add said item to created PC and equip it
4. Roll Stealth Skill check

**Screenshots**
image

**Version Numbers**
Tested on v12 Build 331 both with and without Core Book compendium.
This is using Imperium Maledictum 1.3.1
There were no extra modules.

### PR DESCRIPTION
**Pull request by Tiamanti**
Fix for #27 
Checked with PCs and NPCs
A bit of a long condition but I don't think it merits a helper function on it's own.

### CODE REVIEW

File: src/system/config.js [hunk 1]
```diff
@@ -816,7 +816,23 @@ const IMPMAL = {
...
+           system: {
+               transferData : {
+                   documentType: "Actor"
+               },
+               scriptData : [{
+                   label : "Disadvantage when Wearing Armour with Loud trait",
+                   trigger : "dialog",
+                   script : "args.disadvantage++;",
+                   options : {
+                       hideScript : "return args.data.skill !== 'stealth' || !args.data.actor.itemTypes.equipped.protection.find(i => i.system.traits.list.find(i => i.key == 'loud'))",
```
Comment (moo-man) [inline src/system/config.js:830]: So this can be cleaned up.

If you add `equipTransfer : true` to the `transferData` object, this effect will only be applied to the Actor if the owning Item is equipped, so you really only need to check if stealth is being tested.

Comment (Tiamanti) [reply src/system/config.js:830]: It works but doesn't replace the condition.
The other thing is this should apply only when equipped item is a "protection" item.
Most guns have "Loud" and we don't want them to apply here.
Is there another transferData option that could filter this down?

Comment (moo-man) [reply src/system/config.js:830]: Maybe `return args.data.skill !== 'stealth' || this.item.type != "armour"`

Comment (Tiamanti) [reply src/system/config.js:830]: Sadly no.
```javascript
return args.data.skill !== 'stealth' || this.item.type != 'protection'
```
The issue is if actor has a weapon and protection equipped the item provided is always the weapon.

Comment (Tiamanti) [reply src/system/config.js:831]: I see that transferData can have filter option but I can't seem to get it to work.

Comment (moo-man) [reply src/system/config.js:831]: Filter is not relevant here, I will need to think on what to do for this, perhaps separate weapon and armor trait effects.

Comment (moo-man) [reply src/system/config.js:831]: Right, that hasn't been updated properly since `options` was removed.

Regardless, I think there may be other cases where it's simpler to have a separate `weaponTraitEffects` and `armourTraitEffects`. This is the first time a consolidation option has been relevant so I'm not sure it's worth adding it yet.

Comment (Tiamanti) [reply src/system/config.js:831]: Another option would be if we're consolidating the scripts just have an items array field that pools all the items that have the same script. (with consolidation there in case of multiple identical items equipped).

Then the hideScript would just run find over them and since it's the rightmost item it would only get triggered when it's a skill roll.

Comment (Tiamanti) [reply src/system/config.js:831]: Yeah this seems roughly fine option on the surface.
Changing else in _consolidateScripts
```javascript
else 
{
    const index = consolidated.findIndex(s => isSameScript(script, s));
    const consolidatedScript = consolidated.at(index);
    if (Object.prototype.hasOwnProperty.call(consolidatedScript.context, 'items')) 
    {
        consolidatedScript.context.items.push(script.item);
    }
    else
    {
        consolidatedScript.context.items = [consolidatedScript.context.item, script.item];
    }
    existing.scriptCount++;
}
```
then hide script looks like this
```javascript
return args.data.skill !== 'stealth' || (!this?.items?.find(i => i.type == 'protection') && this.item.type != 'protection')
```
---

The issue that I just noticed though is that all instances of effect apply if this passes...
Because if I read this correctly ```existing.scriptCount++;``` adds all instances of script and not if they all pass.
So if you have 2 pieces of Loud protection and 1 Loud gun you get 3 levels of disadvantage instead of 2.

Your idea of splitting weaponTraitEffects and armourTraitEffects might be the optimal solution.

Comment (Tiamanti) [reply src/system/config.js:831]: For now I think the simplest thing would be to not use traitEffects and instead just revert to the first approach.
computeFields in skill-dialog
```javascript
computeFields()
{
    if (this.data.skill === "stealth")
    {
        const loudProtectionItems = this.data.actor.itemTypes.equipped.protection.filter(i => i.system.traits.list.filter(i => i.key === "loud")).length || 0;
        if (loudProtectionItems > 0) 
        {
            this.disCount += loudProtectionItems;
            this.tooltips.add("disadvantage", loudProtectionItems, game.i18n.localize("IMPMAL.LoudArmourTooltip"));
        }
    }
    super.computeFields();
}
```
One downside is that it doesn't show up in PassiveEffects but considering that it's the most common weapon/armour trait I think it's fine.

Comment (Tiamanti) [reply src/system/config.js]: @moo-man I've restored the original option just slightly refactored.
I think it makes sense without splitting the weaponTraitEffects and armourTraitEffects which is going to be a larger job.

**Comment by moo-man** [comment]
I've split the config effects into weapon and protection types so the config solution should work. Let me know if anything needs adjustment.

**Comment by Tiamanti** [comment]
> I've split the config effects into weapon and protection types so the config solution should work. Let me know if anything needs adjustment.

Nope. It works fine.
